### ISSUE TITLE
[BUG] `(2^3)-1` Does Not Show As Prime

### ISSUE THREAD

**Issue by Danc2050** [TPU-Mersenne-Prime-Search/TensorPrime#24]
It may be just be these smaller numbers but, in the Tensorflow implementation, `(2^3)-1` and `(2^2)-1` do not show up as prime, though both are. If it's only 'cause its small, it's probably not a priority, but if it is a sign of a math error (and not my error) going on, that will obviously trickle up to other exponents.

![image](https://user-images.githubusercontent.com/32185616/154617102-dbe6e5dc-09f4-43a5-987e-c6bb2a03c602.png)

**Comment by tdulcet** [comment]
I do not believe 2²-1 is possible to PRP test, but 2³-1 should work. This issue is this line: https://github.com/TPU-Mersenne-Prime-Search/TensorPrime/blob/a86883bc48e52da7d3584d9420985cda5553fcc5/prptest.py#L14-L15 For type 3 residues it would be `s == 9 % n` as I did in my original PRP example programs (or more precisely `s == (a * a) % n`, where `a` is the PRP base), although they should of course use type 1 residues by default...

**Comment by WillFarris** [comment]
From Josh in Discord this morning:

> As for  exponents 2 and 3 not working, that makes perfect sense since there's no logic for checking if the prime we're testing is less than 9; at the end, it just checks if the remaining residue is 9, not if it's in the same equivalence class. (Though now that I think about it I'm not even sure if exponents that low could even pass the sig length/exponent checks my program does at the beginning.) Definitely should make a note about that in the README. 

I will make a note of this in the README, but I think we should consider this expected behavior of our program. These are the only known mersenne numbers which appear to return incorrect results.

**Comment by tdulcet** [comment]
See my comment above.
